import { Injectable, signal } from '@angular/core';
import { FriendlySpace } from '../models/friendly-space';

@Injectable({
  providedIn: 'root',
})
export class FriendlySpacesService {
  private readonly friendlySpaces = signal<FriendlySpace[]>([
    {
      id: 'cullera-fruteria-la-vega',
      name: 'Frutería La Vega',
      categoryId: 'food',
      address: 'C/ Rei en Jaume, 9, Cullera',
      latitude: 39.163708115921686,
      longitude: -0.25365700086954207,
      googleMapsUrl: 'https://maps.app.goo.gl/rEHSr5rpGzxmYLKs9',
      description: 'Espacio amigo de la lactancia materna.',
      isActive: true,
    },
    {
      id: 'cullera-panaderia-antonio-sanchez',
      name: 'Panadería Antonio Sánchez',
      categoryId: 'food',
      address: 'Plaza de la Libertad, 1, Cullera',
      latitude: 39.16428253334542,
      longitude: -0.2530437225748683,
      googleMapsUrl: 'https://maps.app.goo.gl/A6LEQLhyKeuwyMyeA',
      description: 'Espacio amigo de la lactancia materna.',
      isActive: true,
    },
    {
      id: 'cullera-forn-escriva',
      name: 'Forn Escrivà',
      categoryId: 'food',
      address: 'C/ Valencia, 222, Cullera',
      latitude: 39.17168844386194,
      longitude: -0.2593408189204469,
      googleMapsUrl: 'https://maps.app.goo.gl/6rjANxKdCng5Pajx6',
      description: 'Espacio amigo de la lactancia materna.',
      isActive: true,
    },
    {
      id: 'cullera-herboristeria-sauco',
      name: 'Herboristería Sauco',
      categoryId: 'food',
      address: 'C/ Rei en Jaume, 1, Cullera',
      latitude: 39.16395584801198,
      longitude: -0.253350351342985,
      googleMapsUrl: 'https://maps.app.goo.gl/PbSez3Nb8HRypNXD7',
      description: 'Herboristería, dietética y alimentación ecológica.',
      isActive: true,
    },
    {
      id: 'cullera-la-candy',
      name: 'La Candy',
      categoryId: 'food',
      address: 'Plaza de la Virgen, 31, Cullera',
      latitude: 39.1637244263545,
      longitude: -0.2546711053934834,
      googleMapsUrl: 'https://maps.app.goo.gl/hBuNXedqzamp9ZSq6',
      description: 'Tienda de chuches.',
      isActive: true,
    },
    {
      id: 'cullera-la-terraza-de-julieta',
      name: 'La Terraza de Julieta',
      categoryId: 'restaurants',
      address: 'Calle Poeta Miguel Hernández, 8, Cullera',
      latitude: 39.16475417672589,
      longitude: -0.24399896635783672,
      googleMapsUrl: 'https://maps.app.goo.gl/6JM4JkMDnp4HnYwf6',
      description: 'Cafetería – Gastrobar.',
      isActive: true,
    },
    {
      id: 'cullera-los-pamplonicas',
      name: 'Los Pamplonicas',
      categoryId: 'food',
      address: 'C/ Ciudades Unidas, 2, Cullera',
      latitude: 39.18197184328208,
      longitude: -0.23221465244794928,
      googleMapsUrl: 'https://maps.app.goo.gl/oezNYzwfkp2auKvr7',
      description: 'Alimentación y prensa.',
      isActive: true,
    },
    {
      id: 'cullera-angara-camos',
      name: 'Ángara Camós',
      categoryId: 'fashion',
      address: 'C/ Muñoz Degrain, 1 bajo, Cullera',
      latitude: 39.16431875862876,
      longitude: -0.25443455004988585,
      googleMapsUrl: 'https://maps.app.goo.gl/rMV3ixtNnq4tFUEr6',
      description: 'Joyería y complementos.',
      isActive: true,
    },
    {
      id: 'cullera-paco-camos',
      name: 'Paco Camós',
      categoryId: 'fashion',
      address: 'C/ Cabañal, 16 bajo, Cullera',
      latitude: 39.16415986004465,
      longitude: -0.24405014356611862,
      googleMapsUrl: 'https://maps.app.goo.gl/Kv71edRwaGAtAZfH6',
      description: 'Bisutería y complementos.',
      isActive: true,
    },
    {
      id: 'cullera-noah',
      name: 'Noah',
      categoryId: 'fashion',
      address: 'C/ De la Sèquia, 38, Cullera',
      latitude: 39.164885273060854,
      longitude: -0.25515974291159327,
      googleMapsUrl: 'https://maps.app.goo.gl/WdYVbpawhr7DNWwt8',
      description: 'Moda y complementos.',
      isActive: true,
    },
    {
      id: 'cullera-calzados-elche',
      name: 'Calzados Elche',
      categoryId: 'fashion',
      address: 'C/ Cabañal, 9, Cullera',
      latitude: 39.16439136562297,
      longitude: -0.2445179308927345,
      googleMapsUrl: 'https://maps.app.goo.gl/HFh1RFrjajVHPrUk9',
      description: 'Calzado y complementos.',
      isActive: true,
    },
    {
      id: 'cullera-mn-intima',
      name: 'MN Íntima',
      categoryId: 'fashion',
      address: 'Passeig Dr. Alemany, 16, Cullera',
      latitude: 39.16388663791612,
      longitude: -0.255085196051208,
      googleMapsUrl: 'https://maps.app.goo.gl/6RU9Q9LB9c5YBBjKA',
      description: 'Lencería y corsetería.',
      isActive: true,
    },
    {
      id: 'cullera-don-kiko',
      name: 'Don Kiko',
      categoryId: 'fashion',
      address: 'C/ Cabañal, 14, Cullera',
      latitude: 39.16418143364571,
      longitude: -0.24455023836571466,
      googleMapsUrl: 'https://maps.app.goo.gl/jTTP68FV51n5aW1WA',
      description: 'Comercio de moda para hombre y mujer.',
      isActive: true,
    },
    {
      id: 'cullera-mayoral',
      name: 'Mayoral Cullera',
      categoryId: 'fashion',
      address: 'C/ Baix, 1, Cullera',
      latitude: 39.16547350568414,
      longitude: -0.25560589561554675,
      googleMapsUrl: 'https://maps.app.goo.gl/WbmcgXtzysgZwtcZ6',
      description: 'Tienda de ropa para niños y niñas.',
      isActive: true,
    },
    {
      id: 'cullera-dengue',
      name: 'Dengue',
      categoryId: 'fashion',
      address: 'Calle La Marina, 39 bajo, Cullera',
      latitude: 39.16241878889642,
      longitude: -0.2537362265374509,
      googleMapsUrl: 'https://maps.app.goo.gl/jpeTapzrU5uPw1ma7',
      description: 'Indumentària valenciana.',
      isActive: true,
    },
    {
      id: 'cullera-la-lluna-de-linfant',
      name: 'La Lluna de l’Infant',
      categoryId: 'fashion',
      address: 'Carrer Rey Don Jaime, 1, Cullera',
      latitude: 39.16404286151701,
      longitude: -0.2533721181242295,
      googleMapsUrl: 'https://maps.app.goo.gl/j4oiMvpzSY7kayX56',
      description: 'Moda infantil y puericultura.',
      isActive: true,
    },
    {
      id: 'cullera-xipinines',
      name: 'Xipinines',
      categoryId: 'books_gifts',
      address: 'Plaza del Doctor José Mongrell, 11, Cullera',
      latitude: 39.16509046265196,
      longitude: -0.2455518126406031,
      googleMapsUrl: 'https://maps.app.goo.gl/PwRDHmt8Bj4kREQB6',
      description: 'Juguetes educativos.',
      isActive: true,
    },
    {
      id: 'cullera-ines-llibreria-papereria',
      name: 'Inés Llibreria Papereria',
      categoryId: 'books_gifts',
      address: 'C/ Rey Don Jaime, 3, Cullera',
      latitude: 39.16382898263456,
      longitude: -0.25354260413047475,
      googleMapsUrl: 'https://maps.app.goo.gl/xcfH4izp6jjNWcgu6',
      description: 'Librería y papelería.',
      isActive: true,
    },
    {
      id: 'cullera-naranja-y-limon',
      name: 'Naranja y Limón',
      categoryId: 'books_gifts',
      address: 'C/ Cabañal, 13, Cullera',
      latitude: 39.16426490044833,
      longitude: -0.24318773550128037,
      googleMapsUrl: 'https://maps.app.goo.gl/5ruwTsR5bKAeVE6y5',
      description: 'Artículos de regalo y decoración.',
      isActive: true,
    },
    {
      id: 'cullera-personalitzat-cullera',
      name: 'Personalitza’t Cullera',
      categoryId: 'books_gifts',
      address: 'C/ Rey Don Jaime, 12, Cullera',
      latitude: 39.1639780239915,
      longitude: -0.2535442334242838,
      googleMapsUrl: 'https://maps.app.goo.gl/RTjJnGKagMYDRQa46',
      description: 'Tienda de productos personalizados.',
      isActive: true,
    },
    {
      id: 'cullera-papeleria-kevin',
      name: 'Papelería Kevin',
      categoryId: 'books_gifts',
      address: 'C/ Ateneo Musical, 26, Cullera',
      latitude: 39.163210590675085,
      longitude: -0.25422971290839913,
      googleMapsUrl: 'https://maps.app.goo.gl/EQRP3Ff1joLn9FX26',
      description: 'Papelería, librería y regalos.',
      isActive: true,
    },
    {
      id: 'cullera-gisell-milan-estetica-nails',
      name: 'Gisell Milán Estética & Nails',
      categoryId: 'beauty',
      address: 'C/ Colón, 25, Cullera',
      latitude: 39.162142673686645,
      longitude: -0.25085897130072576,
      googleMapsUrl: 'https://maps.app.goo.gl/qN9uXQSJxXPDGb9p8',
      description: 'Centro de estética.',
      isActive: true,
    },
    {
      id: 'cullera-clinica-essence',
      name: 'Clínica Essence',
      categoryId: 'health',
      address: 'C/ Méndez Núñez, 1, bajo izquierdo, Cullera',
      latitude: 39.16641429256101,
      longitude: -0.2445904858210968,
      googleMapsUrl: 'https://maps.app.goo.gl/7KznT2FvtqNq1RFs5',
      description: 'Clínica de fisioterapia.',
      isActive: true,
    },
    {
      id: 'cullera-siveo',
      name: 'SIVEO',
      categoryId: 'health',
      address: 'C/ Ateneo Musical, 62, Cullera',
      latitude: 39.161755659413615,
      longitude: -0.25182202880101706,
      googleMapsUrl: 'https://maps.app.goo.gl/xo26ddAf4cvs68Hq6',
      description: 'Óptica y centro auditivo.',
      isActive: true,
    },
    {
      id: 'cullera-farmacia-salinas',
      name: 'Farmacia Salinas CB',
      categoryId: 'health',
      address: 'Av. Doctor Alemany, 38, Cullera',
      latitude: 39.16357194051015,
      longitude: -0.25571726466065015,
      googleMapsUrl: 'https://maps.app.goo.gl/96SzjdA5EFvQLh1P9',
      description: 'Farmacia.',
      isActive: true,
    },
    {
      id: 'cullera-farmacia-margarita-gonzalez',
      name: 'Farmacia Margarita González',
      categoryId: 'health',
      address: 'Av. del Racó, Florazar 1, Cullera',
      latitude: 39.17250472454693,
      longitude: -0.24241258833609944,
      googleMapsUrl: 'https://maps.app.goo.gl/coGE12WAdueke7TX8',
      description: 'Farmacia.',
      isActive: true,
    },
    {
      id: 'cullera-farmacia-el-raco',
      name: 'Farmacia El Racó',
      categoryId: 'health',
      address: 'C/ Jaume Roig, 10, Cullera',
      latitude: 39.18072590478542,
      longitude: -0.23604521275927354,
      googleMapsUrl: 'https://maps.app.goo.gl/DhjpaFSFDewLSK1MA',
      description: 'Farmacia.',
      isActive: true,
    },
    {
      id: 'cullera-cafeteria-plaza',
      name: 'Cafetería Plaza',
      categoryId: 'restaurants',
      address: 'Plaza Andrés Piles, Cullera',
      latitude: 39.162194896666534,
      longitude: -0.24941217808305063,
      googleMapsUrl: 'https://maps.app.goo.gl/vwSeBgenawjKnbqR8',
      description: 'Cafetería.',
      isActive: true,
    },
    {
      id: 'cullera-sucre-cafeteria',
      name: 'Sucre Cafetería',
      categoryId: 'restaurants',
      address: 'Ronda Joan Fuster, 8, Cullera',
      latitude: 39.16015362215675,
      longitude: -0.2503831340559101,
      googleMapsUrl: 'https://maps.app.goo.gl/QXbvfFw53dg8W4FJ7',
      description: 'Cafetería y panadería.',
      isActive: true,
    },
    {
      id: 'cullera-gaitos-pesca',
      name: 'Gaitos Pesca',
      categoryId: 'others',
      address: 'Avenida del Puerto, 11, Cullera',
      latitude: 39.1609378051822,
      longitude: -0.25481944451287086,
      googleMapsUrl: 'https://maps.app.goo.gl/FC2mPyGtMRhyaNVd9',
      description: 'Tienda de artículos para la pesca.',
      isActive: true,
    },
    {
      id: 'cullera-milar-senen-ortega',
      name: 'Milar Senen Ortega',
      categoryId: 'others',
      address: 'Plaça Sant Isidre, 13, Cullera',
      latitude: 39.16355651149734,
      longitude: -0.25684639464691117,
      googleMapsUrl: 'https://maps.app.goo.gl/BofPb5t6yA8ygeob8',
      description:
        'Venta de electrodomésticos e instalación de aires acondicionados.',
      isActive: true,
    },
    {
      id: 'cullera-electronday',
      name: 'Electronday',
      categoryId: 'others',
      address: 'C/ 25 de Abril, 53 bajo, Cullera',
      latitude: 39.163763570739086,
      longitude: -0.24744905720731186,
      googleMapsUrl: 'https://maps.app.goo.gl/tK5qcsz1qY75dDcW8',
      description: 'Iluminación y electricidad.',
      isActive: true,
    },
    {
      id: 'cullera-cafe-bar-manantial',
      name: 'Café Bar Manantial',
      categoryId: 'restaurants',
      address: 'Passatge L’Ullal, 2 bajo, Cullera',
      latitude: 39.162175292310465,
      longitude: -0.2483148308135999,
      googleMapsUrl: 'https://maps.app.goo.gl/9VRXRpkBVho7ktBW6',
      description: 'Almuerzos, comidas y cenas.',
      isActive: true,
    },
    {
      id: 'cullera-inka-estilisme',
      name: 'Inka Estilisme',
      categoryId: 'beauty',
      address: 'C/ del Mar, 14, Cullera',
      latitude: 39.163868822582415,
      longitude: -0.2518497245457407,
      googleMapsUrl: 'https://maps.app.goo.gl/kkcKR3skNSBxDc8T8',
      description: 'Peluquería.',
      isActive: true,
    },
    {
      id: 'cullera-maria-jose-font-estilistes',
      name: 'Mª José Font Estilistes',
      categoryId: 'beauty',
      address: 'C/ Poeta Miguel Hernández, 3, Cullera',
      latitude: 39.16464886270825,
      longitude: -0.24428606248950396,
      googleMapsUrl: 'https://maps.app.goo.gl/muarAKcFok5aAfY66',
      description: 'Peluquería.',
      isActive: true,
    },
    {
      id: 'cullera-peluqueria-low-cost-milano',
      name: 'Peluquería Low Cost Milano',
      categoryId: 'beauty',
      address: 'Calle La Marina, 28, Cullera',
      latitude: 39.16207784423799,
      longitude: -0.2533294502327527,
      googleMapsUrl: 'https://maps.app.goo.gl/LcVyLA8SyBitgZCg7',
      description: 'Peluquería.',
      isActive: true,
    },
    {
      id: 'cullera-paco-perfumerias',
      name: 'Paco Perfumerías',
      categoryId: 'beauty',
      address: 'Avinguda Blasco Ibáñez, 3, Cullera',
      latitude: 39.16525895375007,
      longitude: -0.24378767615371247,
      googleMapsUrl: 'https://maps.app.goo.gl/bgPtRodqfPdfTipx9',
      description: 'Perfumería.',
      isActive: true,
    },
    {
      id: 'cullera-paula-torres',
      name: 'Paula Torres',
      categoryId: 'health',
      address: 'C/ La Bega, 15, Cullera',
      latitude: 39.16168448729655,
      longitude: -0.25367713392506636,
      googleMapsUrl: 'https://maps.app.goo.gl/76Bj3UQN5QUUCGMR7',
      description: 'Clínica dental.',
      isActive: true,
    },
    {
      id: 'cullera-clinica-bardana',
      name: 'Fisioterapia Clínica Bardana',
      categoryId: 'health',
      address: 'Carrer Caminàs dels Hòmens, 5, Cullera',
      latitude: 39.163701537586576,
      longitude: -0.24600189045972298,
      googleMapsUrl: 'https://maps.app.goo.gl/EgdwrNtnaHyv8zgS9',
      description:
        'Fisioterapia, osteopatía, suelo pélvico y fisioterapia pediátrica.',
      isActive: true,
    },
    {
      id: 'cullera-farmacia-macarena-peiro',
      name: 'Farmacia Macarena Peiro',
      categoryId: 'health',
      address: 'Avda 25 de Abril, 64, Cullera',
      latitude: 39.16404468182542,
      longitude: -0.2465856875627037,
      googleMapsUrl: 'https://maps.app.goo.gl/CmiPCz9pAtavwQaMA',
      description: 'Oficina de farmacia.',
      isActive: true,
    },
    {
      id: 'cullera-farmacia-carmen-garcia-gorrita',
      name: 'Farmacia Carmen García-Gorrita Moltó',
      categoryId: 'health',
      address: 'Av. Diagonal del País Valencià, 33, Cullera',
      latitude: 39.16216607366836,
      longitude: -0.2516618350300105,
      googleMapsUrl: 'https://maps.app.goo.gl/8JbVFEfvKU6FbzeQ8',
      description: 'Farmacia.',
      isActive: true,
    },
    {
      id: 'cullera-caixa-popular',
      name: 'Caixa Popular',
      categoryId: 'others',
      address: 'Av. Doctor Alemany, 22, Cullera',
      latitude: 39.16394470498962,
      longitude: -0.2552375628625741,
      googleMapsUrl: 'https://maps.app.goo.gl/AKaZ4tdfCBW6rqKc9',
      description: 'Entidad financiera.',
      isActive: true,
    },
    {
      id: 'cullera-loterias-sant-antoni',
      name: 'Administración de Loterías Sant Antoni',
      categoryId: 'others',
      address: 'Plaza Mongrell, 10 bajo, Cullera',
      latitude: 39.16503133906416,
      longitude: -0.24510128402888057,
      googleMapsUrl: 'https://maps.app.goo.gl/qV3n3K42YiG912FB8',
      description: 'Comercio de juegos de azar.',
      isActive: true,
    },
  ]);

  getFriendlySpaces(): FriendlySpace[] {
    return this.friendlySpaces().filter((space) => space.isActive);
  }

  getAdminFriendlySpaces(): FriendlySpace[] {
    return this.friendlySpaces();
  }

  addFriendlySpace(space: FriendlySpace): void {
    this.friendlySpaces.update((spaces) => [...spaces, space]);
  }

  updateFriendlySpace(updatedSpace: FriendlySpace): void {
    this.friendlySpaces.update((spaces) =>
      spaces.map((space) =>
        space.id === updatedSpace.id ? updatedSpace : space,
      ),
    );
  }

  deleteFriendlySpace(spaceId: string): void {
    this.friendlySpaces.update((spaces) =>
      spaces.filter((space) => space.id !== spaceId),
    );
  }
}
